// Generated by CoffeeScript 1.8.0
var expiry, moment, storage, token;

moment = require('moment');

token = 'current';

expiry = 30000;

storage = module.exports = {
  clear: function(app) {
    return app.set(token, {});
  },
  set: function(app, key) {
    var data;
    data = app.get(token);
    if (data == null) {
      data = {};
    }
    data[key] = moment().add(expiry, 'm').unix();
    return app.set(token, data);
  },
  exist: function(app, key) {
    var data, item;
    data = app.get(token);
    if (data != null) {
      item = data[key];
      if (item != null) {
        if (moment().unix() > item) {
          delete data[key];
          return false;
        } else {
          return true;
        }
      } else {
        return false;
      }
    } else {
      return false;
    }
  }
};
