// Generated by CoffeeScript 1.8.0
var fs, input, output, path;

fs = require('fs');

path = require('path');

input = path.resolve('input');

output = path.resolve('output');

exports.bind = function(app) {
  return app.get('/apis/questions/next', function(req, res) {
    var content, file, inputs, json, outputs, _i, _len;
    inputs = fs.readdirSync(input);
    outputs = fs.readdirSync(output);
    for (_i = 0, _len = inputs.length; _i < _len; _i++) {
      file = inputs[_i];
      if (output.indexOf(file) < 0) {
        content = fs.readFileSync(path.join(input, file), {
          encoding: 'utf8'
        });
        json = {
          file: file,
          data: JSON.parse(content)
        };
        return res.status(200).send(json);
      }
    }
    return res.status(404).send({});
  });
};
